---
- name: Do Homework 1
  hosts: all
  user: ansible
  become: yes
  tasks:
#task number one
  - name: Install httpd web-server
    yum:
        name:
          - firewalld
          - httpd
        state: latest
#task number two
  - name: permit traffic in default zone for https service
    firewalld:
      service: https
      permanent: yes
      state: enabled

  - name: Open ports
    firewalld:
      port: 80/tcp
      permanent: yes
      state: enabled
  - name: Cretae welcome file
    ansible.builtin.shell: echo "Welcome to my web server" >> /var/www/html/index.html
#Start httpd service
  - name: Start services
    service:
      name: httpd 
      state: started
#Check is service is up and running or not    
  - name: checking service status
    command: systemctl status "{{ item }}"
    with_items:
     - firewalld
     - httpd
    register: result
    ignore_errors: yes

  - name: showing report
    debug:
     var: result  
